### ISSUE TITLE
Datenbank nicht da

### ISSUE THREAD

**Issue by textrixx** [MarvinFret/LWV#1]
Wenn ich das Projekt laut Doku laufen lasse, fehlt noch die Datenbank:
/Backend/database/database.sqlite) does not exist.

**Comment by MarvinFret** [comment]
Hallo Marco,

das ist komisch. Ich hänge dir die Datenbank an, damit du sie in den
besagten Ordner einfügen kannst.

Viele Grüße
Marvin

Am Do., 22. Apr. 2021 um 08:55 Uhr schrieb Marco Mertens <
***@***.***>:

**Comment by textrixx** [comment]
Hi Marvin, lokal wird einfach die Datei nicht automatisch angelegt. Das funktioniert nur, wenn du ein touch database.sqlite und dann migrate und db:seed machst.

**Comment by textrixx** [comment]
@MarvinFret  Oder schick die DB noch einmal an marco.mertens@lv.de. Dann verteil ich die weiter.
