### ISSUE TITLE
Doku stimmt nicht ganz

### ISSUE THREAD

**Issue by textrixx** [MarvinFret/LWV#2]
Unter 2. muss es npm start, nicht serve heißen. serve existiert als command nicht. 

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

Oder lässt du das über das serve package laufen?

**Comment by MarvinFret** [comment]
Sorry, npm run start ist das richtige Kommando.

Am Do., 22. Apr. 2021 um 11:00 Uhr schrieb Marco Mertens <
***@***.***>:
